# QA System Configuration Example

# Google Cloud API Settings
API_KEY: "your-google-api-key"  # Required for Generative AI and Vision AI
GOOGLE_CLOUD_PROJECT: "your-project-id"  # Required for Vision AI

# Base Directory Settings
BASE_DIR: "."  # Base directory for document processing

# Document Processing Settings
MAX_CHUNK_SIZE: 1000  # Maximum size of text chunks for processing

# File Exclusion Patterns (glob patterns)
EXCLUDE_PATTERNS:
  - "**/.*/**"  # Exclude all files and directories that start with a dot
  - "**/_*/**"

# Vector Store Settings
VECTOR_STORE:
  TYPE: "chroma"  # Vector store type
  PERSIST_DIRECTORY: "./vector_store"  # Directory to persist vector store
  COLLECTION_NAME: "qa_documents"  # Name of the vector store collection
  DISTANCE_METRIC: "cosine"  # Distance metric for similarity search
  TOP_K: 5  # Number of similar documents to retrieve

# Query Engine Settings
QUERY_ENGINE:
  MAX_TOKENS: 2048  # Maximum tokens for query response
  TEMPERATURE: 0.7  # Temperature for response generation
  TOP_P: 0.95  # Top-p sampling parameter
  RESPONSE_MODE: "comprehensive"  # Response generation mode
  SIMILARITY_THRESHOLD: 0.7  # Minimum similarity score for relevant documents

# Logging Settings
LOGGING:
  LEVEL: "INFO"  # Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  FORMAT: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  DATE_FORMAT: "%Y-%m-%d %H:%M:%S"
  LOG_FILE: "logs/qa_system.log"  # Log file path

# System Settings
SYSTEM:
  TIMEOUT: 30  # Default timeout for operations in seconds
  MAX_RETRIES: 3  # Maximum number of retries for failed operations
  BATCH_SIZE: 10  # Batch size for processing multiple documents 