# QA System Configuration

# Logging Configuration
LOGGING:
  LEVEL: "INFO"
  LOG_FILE: "logs/qa_system.log"

# Security & API Configuration
SECURITY:
  GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
  GOOGLE_CLOUD_PROJECT: ${GOOGLE_CLOUD_PROJECT}
  GOOGLE_VISION_API_KEY: ${GOOGLE_VISION_API_KEY}

# File Scanner Configuration
FILE_SCANNER:
  DOCUMENT_PATH: "./docs"
  ALLOWED_EXTENSIONS:
    - "txt"
    - "md"
    - "pdf"
  EXCLUDE_PATTERNS:
    - ".*"
    - "__pycache__"
    - "*.pyc"
  HASH_ALGORITHM: "sha256"
  SKIP_EXISTING: true

# Document Processing Configuration
DOCUMENT_PROCESSING:
  MAX_CHUNK_SIZE: 3072
  MIN_CHUNK_SIZE: 1024
  CHUNK_OVERLAP: 768
  CONCURRENT_TASKS: 6
  BATCH_SIZE: 50
  PRESERVE_SENTENCES: true

# Vector Store Configuration
VECTOR_STORE:
  TYPE: "chroma"
  PERSIST_DIRECTORY: "./data/vector_store"
  COLLECTION_NAME: "qa_documents"
  DISTANCE_METRIC: "cosine"
  TOP_K: 40
