# QA System Configuration

# Logging Configuration
LOGGING:
  LEVEL: "INFO"
  LOG_FILE: "logs/qa_system.log"

# Security & API Configuration
SECURITY:
  GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
  GOOGLE_CLOUD_REGION: ${GOOGLE_CLOUD_REGION}
  GOOGLE_CLOUD_PROJECT: ${GOOGLE_CLOUD_PROJECT}
  GOOGLE_VISION_API_KEY: ${GOOGLE_VISION_API_KEY}
  GEMINI_API_KEY: ${GEMINI_API_KEY}

# File Scanner Configuration
FILE_SCANNER:
  DOCUMENT_PATH: "./docs"
  ALLOWED_EXTENSIONS:
    - "txt"
    - "md"
    - "pdf"
  EXCLUDE_PATTERNS:
    - ".*"
    - "__pycache__"
    - "*.pyc"
    - "smart-chats"
    - "_template"
    - "Excalidraw"
    - "stylesheets"
    - "Tags.md"
  HASH_ALGORITHM: "sha256"
  SKIP_EXISTING: true

# Document Processing Configuration
DOCUMENT_PROCESSING:
  MAX_CHUNK_SIZE: 3072
  MIN_CHUNK_SIZE: 1024
  CHUNK_OVERLAP: 768
  CONCURRENT_TASKS: 6
  BATCH_SIZE: 50
  PRESERVE_SENTENCES: true

# Vector Store Configuration
VECTOR_STORE:
  TYPE: "chroma"
  PERSIST_DIRECTORY: "./data/vector_store"
  COLLECTION_NAME: "qa_documents"

QUERY:
  # Retrieval/Search Parameters
  DISTANCE_METRIC: "cosine"         # (str) Similarity metric for vector search: "cosine", "euclidean", etc.
  TOP_K: 40                         # (int) Number of top results to retrieve per query

  # Hybrid Scoring/Metadata Boosts
  RECENCY_BOOST: 1.0                # (float) Boost for recent documents (1.0 = neutral, >1.0 = boost, <1.0 = penalty)
  TAG_BOOST: 1.0                    # (float) Boost for tag matches (1.0 = neutral, >1.0 = boost, <1.0 = penalty)
  SOURCE_BOOST: 1.0                 # (float) Boost for preferred sources (1.0 = neutral, >1.0 = boost, <1.0 = penalty)

  # Generation Parameters (for Gemini or LLM response)
  TEMPERATURE: 0.2                  # (float) Controls randomness of generated text (0.0 = deterministic, 1.0 = creative)
  MAX_TOKENS: 512                   # (int) Maximum tokens in generated response
  CONTEXT_WINDOW: 4096              # (int) Number of tokens of context to pass to the model
